/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, EmployerProfile } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateEmployerProfile(options?: Omit<(UseMutationOptions<(EmployerProfile | undefined), DefaultError, Prisma.EmployerProfileCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileCreateArgs, DefaultError, EmployerProfile, true>('EmployerProfile', 'POST', `${endpoint}/employerProfile/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyEmployerProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmployerProfileCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('EmployerProfile', 'POST', `${endpoint}/employerProfile/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyEmployerProfile<TArgs extends Prisma.EmployerProfileFindManyArgs, TQueryFnData = Array<Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findMany`, args, options, fetch);
}

export function useInfiniteFindManyEmployerProfile<TArgs extends Prisma.EmployerProfileFindManyArgs, TQueryFnData = Array<Prisma.EmployerProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findMany`, args, options, fetch);
}

export function useSuspenseFindManyEmployerProfile<TArgs extends Prisma.EmployerProfileFindManyArgs, TQueryFnData = Array<Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyEmployerProfile<TArgs extends Prisma.EmployerProfileFindManyArgs, TQueryFnData = Array<Prisma.EmployerProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findMany`, args, options, fetch);
}

export function useFindUniqueEmployerProfile<TArgs extends Prisma.EmployerProfileFindUniqueArgs, TQueryFnData = Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueEmployerProfile<TArgs extends Prisma.EmployerProfileFindUniqueArgs, TQueryFnData = Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findUnique`, args, options, fetch);
}

export function useFindFirstEmployerProfile<TArgs extends Prisma.EmployerProfileFindFirstArgs, TQueryFnData = Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstEmployerProfile<TArgs extends Prisma.EmployerProfileFindFirstArgs, TQueryFnData = Prisma.EmployerProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/findFirst`, args, options, fetch);
}

export function useUpdateEmployerProfile(options?: Omit<(UseMutationOptions<(EmployerProfile | undefined), DefaultError, Prisma.EmployerProfileUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileUpdateArgs, DefaultError, EmployerProfile, true>('EmployerProfile', 'PUT', `${endpoint}/employerProfile/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyEmployerProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmployerProfileUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('EmployerProfile', 'PUT', `${endpoint}/employerProfile/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertEmployerProfile(options?: Omit<(UseMutationOptions<(EmployerProfile | undefined), DefaultError, Prisma.EmployerProfileUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileUpsertArgs, DefaultError, EmployerProfile, true>('EmployerProfile', 'POST', `${endpoint}/employerProfile/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteEmployerProfile(options?: Omit<(UseMutationOptions<(EmployerProfile | undefined), DefaultError, Prisma.EmployerProfileDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileDeleteArgs, DefaultError, EmployerProfile, true>('EmployerProfile', 'DELETE', `${endpoint}/employerProfile/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, EmployerProfile, Prisma.EmployerProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyEmployerProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.EmployerProfileDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.EmployerProfileDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('EmployerProfile', 'DELETE', `${endpoint}/employerProfile/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.EmployerProfileDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.EmployerProfileDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.EmployerProfileDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateEmployerProfile<TArgs extends Prisma.EmployerProfileAggregateArgs, TQueryFnData = Prisma.GetEmployerProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateEmployerProfile<TArgs extends Prisma.EmployerProfileAggregateArgs, TQueryFnData = Prisma.GetEmployerProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/aggregate`, args, options, fetch);
}

export function useGroupByEmployerProfile<TArgs extends Prisma.EmployerProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EmployerProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.EmployerProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.EmployerProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.EmployerProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.EmployerProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.EmployerProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.EmployerProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByEmployerProfile<TArgs extends Prisma.EmployerProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.EmployerProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.EmployerProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.EmployerProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.EmployerProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.EmployerProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.EmployerProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.EmployerProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/groupBy`, args, options, fetch);
}

export function useCountEmployerProfile<TArgs extends Prisma.EmployerProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.EmployerProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/count`, args, options, fetch);
}

export function useSuspenseCountEmployerProfile<TArgs extends Prisma.EmployerProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.EmployerProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.EmployerProfileCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('EmployerProfile', `${endpoint}/employerProfile/count`, args, options, fetch);
}

export function useCheckEmployerProfile<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; companyId?: string; title?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('EmployerProfile', `${endpoint}/employerProfile/check`, args, options, fetch);
}
