/******************************************************************************
 * This file was generated by ZenStack CLI.
 ******************************************************************************/

/* eslint-disable */

import type { Prisma, StudentProfile } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateStudentProfile(options?: Omit<(UseMutationOptions<(StudentProfile | undefined), DefaultError, Prisma.StudentProfileCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileCreateArgs, DefaultError, StudentProfile, true>('StudentProfile', 'POST', `${endpoint}/studentProfile/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyStudentProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StudentProfileCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('StudentProfile', 'POST', `${endpoint}/studentProfile/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyStudentProfile<TArgs extends Prisma.StudentProfileFindManyArgs, TQueryFnData = Array<Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findMany`, args, options, fetch);
}

export function useInfiniteFindManyStudentProfile<TArgs extends Prisma.StudentProfileFindManyArgs, TQueryFnData = Array<Prisma.StudentProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findMany`, args, options, fetch);
}

export function useSuspenseFindManyStudentProfile<TArgs extends Prisma.StudentProfileFindManyArgs, TQueryFnData = Array<Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyStudentProfile<TArgs extends Prisma.StudentProfileFindManyArgs, TQueryFnData = Array<Prisma.StudentProfileGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findMany`, args, options, fetch);
}

export function useFindUniqueStudentProfile<TArgs extends Prisma.StudentProfileFindUniqueArgs, TQueryFnData = Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueStudentProfile<TArgs extends Prisma.StudentProfileFindUniqueArgs, TQueryFnData = Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findUnique`, args, options, fetch);
}

export function useFindFirstStudentProfile<TArgs extends Prisma.StudentProfileFindFirstArgs, TQueryFnData = Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstStudentProfile<TArgs extends Prisma.StudentProfileFindFirstArgs, TQueryFnData = Prisma.StudentProfileGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/findFirst`, args, options, fetch);
}

export function useUpdateStudentProfile(options?: Omit<(UseMutationOptions<(StudentProfile | undefined), DefaultError, Prisma.StudentProfileUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileUpdateArgs, DefaultError, StudentProfile, true>('StudentProfile', 'PUT', `${endpoint}/studentProfile/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyStudentProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StudentProfileUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('StudentProfile', 'PUT', `${endpoint}/studentProfile/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertStudentProfile(options?: Omit<(UseMutationOptions<(StudentProfile | undefined), DefaultError, Prisma.StudentProfileUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileUpsertArgs, DefaultError, StudentProfile, true>('StudentProfile', 'POST', `${endpoint}/studentProfile/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteStudentProfile(options?: Omit<(UseMutationOptions<(StudentProfile | undefined), DefaultError, Prisma.StudentProfileDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileDeleteArgs, DefaultError, StudentProfile, true>('StudentProfile', 'DELETE', `${endpoint}/studentProfile/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, StudentProfile, Prisma.StudentProfileGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyStudentProfile(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.StudentProfileDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.StudentProfileDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('StudentProfile', 'DELETE', `${endpoint}/studentProfile/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.StudentProfileDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.StudentProfileDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.StudentProfileDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateStudentProfile<TArgs extends Prisma.StudentProfileAggregateArgs, TQueryFnData = Prisma.GetStudentProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StudentProfileAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateStudentProfile<TArgs extends Prisma.StudentProfileAggregateArgs, TQueryFnData = Prisma.GetStudentProfileAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.StudentProfileAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/aggregate`, args, options, fetch);
}

export function useGroupByStudentProfile<TArgs extends Prisma.StudentProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StudentProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.StudentProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StudentProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StudentProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StudentProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StudentProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StudentProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByStudentProfile<TArgs extends Prisma.StudentProfileGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.StudentProfileGroupByArgs['orderBy'] } : { orderBy?: Prisma.StudentProfileGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.StudentProfileGroupByOutputType, TArgs['by']> &
    {
        [P in ((keyof TArgs) & (keyof Prisma.StudentProfileGroupByOutputType))]: P extends '_count'
        ? TArgs[P] extends boolean
        ? number
        : Prisma.GetScalarType<TArgs[P], Prisma.StudentProfileGroupByOutputType[P]>
        : Prisma.GetScalarType<TArgs[P], Prisma.StudentProfileGroupByOutputType[P]>
    }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.StudentProfileGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/groupBy`, args, options, fetch);
}

export function useCountStudentProfile<TArgs extends Prisma.StudentProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StudentProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/count`, args, options, fetch);
}

export function useSuspenseCountStudentProfile<TArgs extends Prisma.StudentProfileCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.StudentProfileCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.StudentProfileCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('StudentProfile', `${endpoint}/studentProfile/count`, args, options, fetch);
}

export function useCheckStudentProfile<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; bio?: string; university?: string; major?: string; yearOfStudy?: number; skills?: string; cvUrl?: string; portfolio?: string; github?: string; linkedin?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('StudentProfile', `${endpoint}/studentProfile/check`, args, options, fetch);
}
